site_name: Core Documentation
theme:
  name: material

plugins:
  - search

markdown_extensions: 
  - extra
  - codehilite
  - toc:
      permalink: true
      separator: '_'
  - sane_lists
  - smarty

nav:
  - Home: 'index.md'
  - Pipeline: 'cpu.md'
  - TLB: 'tlb.md'
  - Cache: 'cache.md'
  - Mul: 'mul.md'
  - Div: 'div.md'
  - Framework: 'framework.md'
  - Reference design: 'ip.md'
  - About: 'about.md'
